<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Product>FPVDroneModClient</Product>
        <Version>1.0.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.samboy.dev/v3/index.json
        </RestoreAdditionalProjectSources>
        <RootNamespace>FPVDroneModClient</RootNamespace>
        <Configurations>Debug;Release;UNITY_EDITOR</Configurations>
        <Platforms>AnyCPU</Platforms>
        <PackageId>FPVDroneModClient</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
        <PackageReference Include="BepInEx.Core" Version="5.*"/>
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*"/>
        <PackageReference Include="DXNET" Version="5.0.0"/>
        <PackageReference Include="DXNET.XInput" Version="5.0.0"/>
        <PackageReference Include="UnityEngine.Modules" Version="2019.4.39" IncludeAssets="compile"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Comfort">
            <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="DissonanceVoip">
            <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\DissonanceVoip.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="DrakiaXYZ-BigBrain">
            <HintPath>..\..\..\BepInEx\plugins\DrakiaXYZ-BigBrain.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Sirenix.Serialization">
            <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="spt-reflection">
            <HintPath>..\..\..\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="WTT-ClientCommonLib">
          <HintPath>..\..\..\BepInEx\plugins\WTT-ClientCommonLib\WTT-ClientCommonLib.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ReferencePathWithRefAssemblies Update="C:\Users\pein\.nuget\packages\dxnet.xinput\5.0.0\lib\netstandard2.1\DXNET.XInput.dll"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(MSBuildProjectFullPath).user" Condition="Exists('$(MSBuildProjectFullPath).user')" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="FPVDroneModClient.csproj.user" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Resources\" />
    </ItemGroup>

    <Target Name="CopyToSPT" AfterTargets="AfterBuild" Condition="'$(SPTPath)' != ''">
        <PropertyGroup>
            <ModsDirectoryPath>$(SPTPath)\BepInEx\plugins\$(MSBuildProjectName)</ModsDirectoryPath>
        </PropertyGroup>

        <Message Importance="high" Text="Copying mods to $(ModsDirectoryPath)" />
        <ItemGroup>
            <FilesToCopy Include="$(OutputPath)$(TargetName)$(TargetExt)" />
            <FilesToCopy Include="$(OutputPath)$(TargetName).pdb" />
            <FilesToCopy Include="Resources\**\*" />
        </ItemGroup>
        <Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(ModsDirectoryPath)\%(RecursiveDir)" ContinueOnError="false" />
        <Message Importance="high" Text="Files copied" />
    </Target>
</Project>
