<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Version>0.8.1</Version>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FPVDroneModServer</RootNamespace>
        <Configurations>Debug;Release;UNITY_EDITOR</Configurations>
        <Platforms>AnyCPU</Platforms>
        <SPTModType>Server</SPTModType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SPTarkov.Server.Core" Version="4.1.1" />
      <PackageReference Include="WTT-ServerCommonLib" Version="3.0.3" />
    </ItemGroup>

    <ItemGroup>
        <None Include="$(MSBuildProjectFullPath).user" Condition="Exists('$(MSBuildProjectFullPath).user')" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\db\quests\skier\Images\" />
    </ItemGroup>
</Project>
