<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FPVDroneModServer</RootNamespace>
        <Configurations>Debug;Release;UNITY_EDITOR</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SPTarkov.Server.Core" Version="4.0.3" />
      <PackageReference Include="WTT-ServerCommonLib" Version="2.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="$(MSBuildProjectFullPath).user" Condition="Exists('$(MSBuildProjectFullPath).user')" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="FPVDroneModServer.csproj.user" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="spt-custom">
        <HintPath>..\..\..\BepInEx\plugins\spt\spt-custom.dll</HintPath>
      </Reference>
    </ItemGroup>

    <Target Name="CopyToSPT" AfterTargets="AfterBuild" Condition="'$(SPTPath)' != ''">
        <PropertyGroup>
            <ModsDirectoryPath>$(SPTPath)\SPT\user\mods\$(MSBuildProjectName)</ModsDirectoryPath>
        </PropertyGroup>

        <Message Importance="high" Text="Copying mods to $(ModsDirectoryPath)" />
        <ItemGroup>
            <FilesToCopy Include="$(OutputPath)$(TargetName)$(TargetExt)" />
            <FilesToCopy Include="$(OutputPath)$(TargetName).pdb" />
            <FilesToCopy Include="Resources\**\*" />
        </ItemGroup>
        <Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(ModsDirectoryPath)\%(RecursiveDir)" ContinueOnError="false" />
        <Message Importance="high" Text="Files copied" />
    </Target>
</Project>
